product1 = "//body/div[4]/div[1]/div[4]/div[3]/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/div[3]/div[2]/input[1]"
pdt1_addToCart = "id:add-to-cart-button-2"
recipient_name = "id:giftcard_2_RecipientName"
recipient_email =  "id:giftcard_2_RecipientEmail"
sender_name = "id:giftcard_2_SenderName"