username_txt = "id:user-name"
password_txt = "id:password"
first_name_txt = "id:first-name"
last_name_txt = "id:last-name"
zip_txt = "id:postal-code"
logout = "id:logout_sidebar_link"
side_bar_open = "id:react-burger-menu-btn"
side_bar_close = "id:react-burger-cross-btn"
login_btn = "id:login-button"
shopping_cart = "id:shopping_cart_container"
product_1 = "xpath://*[@id='item_4_title_link']"
add_to_cart_pdt1 = "id:add-to-cart-sauce-labs-backpack"
shp_cart_badge = "xpath://span[@class='shopping_cart_badge']"
checkout_btn = "id:checkout"
continue_btn = "id:continue"
reset_app_state = "id:reset_sidebar_link"
all_products = "xpath://div[contains(@class, 'inventory_item')]//button[contains(@class, 'btn_primary') ]"
inv_list = "xpath://div[@class='inventory_list']"
sort_container = "xpath://*[@class='product_sort_container']"
name_sort_desc = "xpath://select[@class='product_sort_container']/option[@value='za']"
prod_names = "xpath://div[@class='inventory_item_name']"
prod_price_asc = "xpath://select[@class='product_sort_container']/option[@value='lohi']"
prod_prices = "xpath://div[@class='inventory_item_price']"
prod_price_desc = "xpath://select[@class='product_sort_container']/option[@value='hilo']"
item_price = "xpath://div[@class='inventory_item_price']"
item_tax = "xpath://div[@class='summary_tax_label']"
total_bill = "xpath://div[@class='summary_info_label summary_total_label']"
finish_btn = "id:finish"

