email_txt = "id:Email"
password_txt = "id:Password"
login_btn = "id:btnLogin"
header_dropdown = "id:dropdownMenuLinkMainHeader"
logout_element = "xpath://a[@data-target='#logoutModal']"
logout_btn = "xpath://button[@type='button' and contains(text(), 'Log Out')]"
project_finstreet = "xpath://a[@href='/Project/OverView/1211']"
testplan_tab = "xpath://a[contains(text(), 'Test Plan')]"
milestone_tab = "xpath://a[contains(text(), 'Milestones')]"
add_milestone_btn = "xpath://button[contains(text(),'Add Milestone')]"
total_projects = "xpath://h6[@class='font-weight-bold mr-1']"
back_to_dashboard = "xpath://a[@href='/Dashboard/Index' and @class='arrow-back']"
milestone_name_txt = "id:Name"
milestone_desc_txt = "id:Description"
add_milestone_btnConfirm = "id:btnAddEditMilestone"
